### ISSUE TITLE
Qtum electrum wallet not connected version 0.18.15

### ISSUE THREAD

**Issue by Dominic2015** [qtumproject/qtum-electrum#101]
Qtum electrum wallet not connected version 0.18.15,
any solution?

![qtumw](https://user-images.githubusercontent.com/56601063/66849137-b1391b80-ef76-11e9-8860-588a71c10909.JPG)

**Comment by icodeface** [comment]
cannot reproduce on my side, can you go to `Preference` => `Appearance` and enable `Write logs to file`, the open Qtum electrum again, and upload the log files in location `%AppData%/Qtum-Electrum/logs`

**Comment by Dominic2015** [comment]
![image](https://user-images.githubusercontent.com/56601063/67008382-a81c8b80-f0e9-11e9-9c49-4b88eab527d7.png)

well where do i find write logs to file, cannot find it, connection still not possible, 

allthough i allowed qtum in Windows 10 firewall

**Comment by Dominic2015** [comment]
![image](https://user-images.githubusercontent.com/56601063/67008525-f467cb80-f0e9-11e9-8a63-26f79138e7d5.png)
where do i find write logs to file, cannot find it, connection still not possible,

allthough i allowed qtum in Windows 10 firewall

**Comment by Dominic2015** [comment]
![image](https://user-images.githubusercontent.com/56601063/67008576-15c8b780-f0ea-11e9-9eda-777da99478c1.png)

**Comment by Dominic2015** [comment]
also WIndows XP Compatibility mode and firewall forwarding doesnt help

**Comment by Dominic2015** [comment]
dont find the log activation and the log folder

**Comment by Dominic2015** [comment]
![image](https://user-images.githubusercontent.com/56601063/67009124-36ddd800-f0eb-11e9-9471-059c9b4133e5.png)
i deleted Qtum Appdata folder and program folder

**Comment by Dominic2015** [comment]
![image](https://user-images.githubusercontent.com/56601063/67013106-dd79a700-f0f2-11e9-8064-a252f641b976.png)

if i want to install qtum core wallet the program executable disappears itself after installation

**Comment by Dominic2015** [comment]
Does not work on my side, cant access my funds

**Comment by Dominic2015** [comment]
So until now doesnt work

**Comment by Dominic2015** [comment]
Cant not find enable write to logs

**Comment by Dominic2015** [comment]
![image](https://user-images.githubusercontent.com/56601063/67033281-ae286180-f115-11e9-8dbc-0327d5e3eeb5.png)
next problem with web wallet

i cant access my qtum , any help maybe?

**Comment by Dominic2015** [comment]
cant find to activate log
cant connect to server
cant see my balance on block explorer
cant use web wallet
cant install qtum core cause executable disappears after installation

**Comment by Dominic2015** [comment]
![image](https://user-images.githubusercontent.com/56601063/67037223-6c031e00-f11d-11e9-9e48-4e1ff307269c.png)
Doesnt help, im tended to install Windows 10 new, cause the qtum products are the most bad ive ever seen, cant reach my funds and windows completely destroyed thanks

**Comment by Dominic2015** [comment]
ok, listen i had to install Windows 7, 

Windows 10 is not able to connect, so i reinstall Windows 10

How can i extract the private key out of this qtum wallet?

**Comment by icodeface** [comment]
> ok, listen i had to install Windows 7,
> 
> Windows 10 is not able to connect, so i reinstall Windows 10
> 
> is there an online wallet i can put the private keys from that wallet into?
> Where can i use the electrum private keys apart from qtum electrum wallet?

see https://docs.qtum.site/en/QTUM-WebWallet-usage/#4-restore-from-wif

**Comment by Dominic2015** [comment]
![image](https://user-images.githubusercontent.com/56601063/67093143-432c6880-f1b1-11e9-9b0e-05da05488592.png)
the qtum electrum wallet works now great, but if i take the seed and put it into
Mnemonic
![image](https://user-images.githubusercontent.com/56601063/67093192-5e977380-f1b1-11e9-95f9-f3496f4602bc.png)
it shows me up i own 0 qtum, but on my qtum electrum wallet i have over 40
