### ISSUE TITLE
MAC OSX Electrum Wallet NOT SYNCING- RED- HELP!

### ISSUE THREAD

**Issue by rishabhkapoor8711** [qtumproject/qtum-electrum#102]
I tried downloading the uploaded version, however the RED at the bottom right of the window does not turn green after a while. The new version is not verifying the old transactions also. Please help asap. I cannot move my funds. 
<img width="1440" alt="Screenshot 2019-11-07 at 3 59 04 PM" src="https://user-images.githubusercontent.com/26839040/68403546-68dbda80-017d-11ea-9ae7-8cbd7e855bb8.png">

**Comment by icodeface** [comment]
please go to "Settings" and enable "Write logs to file", then reopen qtum electrum, after the status icon becomes red, close the wallet and share the log files in `~/.qtum-electrum/logs`  here

**Comment by icodeface** [comment]
reopen the wallet should fix the issue
