### ISSUE TITLE
wrong negative division in get_target()

### ISSUE THREAD

**Issue by codefairy-bsc** [qtumproject/qtum-electrum#108]
there's a difference between C++ and Python in  negative division.
`t1 = 2 * (nActualSpace - POW_TARGET_TIMESPACE) // 16` in https://github.com/qtumproject/qtum-electrum/blob/master/electrum/blockchain.py#L722
shoule be `t1 = int(2 * (nActualSpace - POW_TARGET_TIMESPACE) / 16)`

**Comment by icodeface** [comment]
thanks!
