### ISSUE TITLE
Qtum-Electrum with Trezor One - can't send coins (wrong address path m/44'/88’/0’/0/0) 

### ISSUE THREAD

**Issue by SereFF1984** [qtumproject/qtum-electrum#112]
Hello! 
Qtum-Electrum-v4.0.11
HD Trezor One, firmware 1.9.4

In March 2020 was created new wallet in Qtum-electrum 0.18.16  with HD Trezor One.
Wrongly selected legacy(p2pkh) with path: m/44’/88’/0’, but it was necessary to choose legacy(p2pkh)(trezor/safe_t web wallet compatiable) with path: m/44’/2301’/0’.
![7](https://user-images.githubusercontent.com/78924710/107677276-21f76180-6cab-11eb-9508-ac222716f71d.png)
Despite this, the wallet was created successfully and I deposit some Qtum coins to it. The coins were deposited successfully.
![9](https://user-images.githubusercontent.com/78924710/107677912-cd081b00-6cab-11eb-8de6-e105bed58fa6.png)
![12](https://user-images.githubusercontent.com/78924710/107678114-0b9dd580-6cac-11eb-8f23-b79b162e5b51.png)
Today I decided to send coins from this wallet but I got an error in Qtum-Electrum and coins didn't send.
![15](https://user-images.githubusercontent.com/78924710/107684337-b82f8580-6cb3-11eb-9207-015911f2a73f.png)
When I try to see my Qtum address with coins in Trezor One, the hardware wallet shows that "wrong address part for selected coin, and then I see on Trezor that path is m/44’/88’/0’/0/0.
![18](https://user-images.githubusercontent.com/78924710/107678011-e9a45300-6cab-11eb-9d4e-5274b4d1371c.png)
![19](https://user-images.githubusercontent.com/78924710/107678016-ee690700-6cab-11eb-8dc7-fb249c8f18b0.png)
If I choose the correct path m/44’/2301’/0’, Qtum-Electrum creates new wallet and Trezor does not give an error, but the wallet addresses are already completely different and empty.
![14](https://user-images.githubusercontent.com/78924710/107678144-12c4e380-6cac-11eb-9486-ec831cf586f2.png)
Is there a solution to this problem? How do I send my coins? Help me please.

**Comment by prusnak** [comment]
I think it's wrong to provide non-functional options in the UI here:

https://github.com/qtumproject/qtum-electrum/blob/1e45671b67f890abbe21166b0a4363f46144c873/electrum/base_wizard.py#L450-L464

And the better code would be:

``` python
if self.plugin is not None and self.plugin.name in ["trezor", "safe_t"]: 
    choices = [ 
        ('standard', 'legacy (p2pkh) (trezor/safe_t web wallet compatiable)', 
         bip44_derivation(0, bip43_purpose=44, coin=constants.net.SLIP_COIN_TYPE)), 
        ('p2wpkh-p2sh', 'p2sh-segwit (p2wpkh-p2sh) (trezor/safe_t web wallet compatiable)', 
         bip44_derivation(0, bip43_purpose=49, coin=constants.net.SLIP_COIN_TYPE)), 
        ('p2wpkh', 'native segwit (p2wpkh) (trezor/safe_t web wallet compatiable)', 
         bip44_derivation(0, bip43_purpose=84, coin=constants.net.SLIP_COIN_TYPE)), 
    ]
else:
    choices = [ 
       ('standard',    'legacy (p2pkh)',            bip44_derivation(0, bip43_purpose=44)), 
       ('p2wpkh-p2sh', 'p2sh-segwit (p2wpkh-p2sh)', bip44_derivation(0, bip43_purpose=49)), 
       ('p2wpkh',      'native segwit (p2wpkh)',    bip44_derivation(0, bip43_purpose=84)), 
    ] 
```

**Comment by icodeface** [comment]
Hi, please try change the coin_name in https://github.com/qtumproject/qtum-electrum/blob/master/electrum/plugins/trezor/trezor.py#L208 to `Bitcoin`, then u can send your qtum out using `m/44’/88’/0’`.

**Comment by icodeface** [comment]
the `88` bip44 coin type issue: https://github.com/satoshilabs/slips/pull/196

**Comment by SereFF1984** [comment]
Thanks for answer but today Qtum-Electrum cannot connect to the network. I tried to uninstall Qtum-Electrum wallet and install it again but still cannot connect. Internet is working fine, the problem is precisely in Qtum network. Are you already solving this problem?
![1](https://user-images.githubusercontent.com/78924710/107750895-b2768600-6d2d-11eb-8786-a7dc35245614.png)

**Comment by icodeface** [comment]
> Thanks for answer but today Qtum-Electrum cannot connect to the network. I tried to uninstall Qtum-Electrum wallet and install it again but still cannot connect. Internet is working fine, the problem is precisely in Qtum network. Are you already solving this problem?
> ![1](https://user-images.githubusercontent.com/78924710/107750895-b2768600-6d2d-11eb-8786-a7dc35245614.png)

the connection issue solved.

**Comment by icodeface** [comment]
both `88` and `2301` worked on old trezor firmware, we keep `88` in case some people need recover his wallet, but the latest firmware breaks the support of `88`.  I will figure out a way to fix this, new Qtum Electrum release coming soon, sorry for the inconvenience.

**Comment by SereFF1984** [comment]
Ok, thanks. Will try to connect. Tell me please will Qtum-Electrum wallet support today's QiSwap airdrop?

**Comment by icodeface** [comment]
> Ok, thanks. Will try to connect. Tell me please will Qtum-Electrum wallet support today's QiSwap airdrop?

don't think so, since trezor doesn't support sending QRC20 Tokens for now.

**Comment by JB395** [comment]
@SereFF1984 do you know Linux/Python, were you able to try the procedure above?

Were you also reporting this issue on Discord or Telegram, or just here?

**Comment by SereFF1984** [comment]
Hi! Thanks for your help! I disabled safety check in Trezor T via trezorctl and then send my coins. 
https://github.com/trezor/trezor-firmware/issues/1471#issuecomment-777731251
This issue can be closed. Happy new year!
