### ISSUE TITLE
QTUM send error with Trezor Model T

### ISSUE THREAD

**Issue by Anlihuha** [qtumproject/qtum-electrum#115]
I have the desktop Qtum Electrum wallet (version 4.0.14) and use it with a Trezor Model T 
(firmware version 2.3.6).  I can log into the Electrum wallet and can see my QTUM balance.
However, when I try to send Qtum to Binance US and need to sign the transaction, I am able to, but the 
transaction fails with the message: 

Runtime Error ('Data Error: Forbidden key path')

I have tried to deposit to Kraken and Crypto.com as well and receive the same error.  My Qtum is therefore
stranded in the Qtum Electrum wallet.

**Comment by icodeface** [comment]
Hi @Anlihuha , please try go to the setting page (click the trezor icon on the right bottom), and change the "Safety Check Level" to "prompt", after sending your Qtum out, change it back to "strict".

<img width="593" alt="WX20210511-144351@2x" src="https://user-images.githubusercontent.com/9477987/117770540-9e2c2180-b267-11eb-86f4-373e75c5b3d4.png">

**Comment by Anlihuha** [comment]
It worked.  Thanks again.
