### ISSUE TITLE
Bump trezor lib version

### ISSUE THREAD

**Issue by puruoni** [qtumproject/qtum-electrum#119]
Error with trezor connection due to low version of trezorctl.
> trezor: (error getting device infos)
    Library version for 'trezor' is incompatible.
    Installed: 0.13.0, Needed: 0.12.0 <= x < 0.13
    Make sure you install it with python3

It should be upgraded.
https://github.com/qtumproject/qtum-electrum/blob/master/electrum/plugins/trezor/trezor.py#L120-L121

like this.
https://github.com/spesmilo/electrum/blob/master/electrum/plugins/trezor/trezor.py#L119-L120

**Comment by icodeface** [comment]
will check

**Comment by icodeface** [comment]
Hi @puruoni are u able to run from the source code ? does the fix works fine ? 
i don't have a trezor to test.

**Comment by puruoni** [comment]
@icodeface 
Thanks for fixing so quickly.
I've had a few errors, but by doing this I was able to boot.
Trezor was also recognized!!

・blsecp256k1
> brew tap cuber/homebrew-libsecp256k1
> brew install libsecp256k1

・protobuf
> pip install protobuf==3.20.3
> export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python

・pyqt5
> brew install pyqt5
> cd /opt/homebrew/Cellar/pyqt@5/5.15.7_1/lib/python3.10/site-packages
> *** In the case of pyenv ***
> cp -pr * /Users/[username]/.pyenv/versions/3.10.8/lib/python3.10/site-packages/.
> echo 'export PATH="/opt/homebrew/opt/qt@5/bin:$PATH"' >> ~/.zshrc
> echo 'export PATH="/opt/homebrew/opt/pyqt@5/5.15.4_1/bin:$PATH"' >> ~/.zshrc
> source ~/.zshrc

Then cloned and configured according to the README.

**Comment by icodeface** [comment]
> @icodeface Thanks for fixing so quickly. I've had a few errors, but by doing this I was able to boot. Trezor was also recognized!!
> 
> ・blsecp256k1
> 
> > brew tap cuber/homebrew-libsecp256k1
> > brew install libsecp256k1
> 
> ・protobuf
> 
> > pip install protobuf==3.20.3
> > export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python
> 
> ・pyqt5
> 
> > brew install pyqt5
> > cd /opt/homebrew/Cellar/pyqt@5/5.15.7_1/lib/python3.10/site-packages
> > *** In the case of pyenv ***
> > cp -pr * /Users/[username]/.pyenv/versions/3.10.8/lib/python3.10/site-packages/.
> > *** In the case of pyenv ***
> > echo 'export PATH="/opt/homebrew/opt/qt@5/bin:$PATH"' >> ~/.zshrc
> > echo 'export PATH="/opt/homebrew/opt/pyqt@5/5.15.4_1/bin:$PATH"' >> ~/.zshrc
> > source ~/.zshrc
> 
> Then cloned and configured according to the README.

glad to hear that, and thanks for the tips, will add to doc

**Comment by puruoni** [comment]
Oh, I just built it from source code, now ledger may not recognize it.
> W | gui.qt.installwizard.InstallWizard | error getting device infos for ledger: Missing libraries for ledger. // Make sure you install it with python3

**Comment by nguis** [comment]
Error with Trezor is not fixed yet

Debugnachricht
  trezor: (error getting device infos)
    Die Version der Programmbibliothek 'trezor' ist inkompatibel.
    Installed: 0.13.0, Needed: 0.12.0 <= x < 0.13
    Achten Sie darauf, es für Python 3 zu installieren

**Comment by nguis** [comment]
any news ? This error has not been fixed yet.

trezor: (error getting device infos)
Library version for 'trezor' is incompatible.
Installed: 0.13.0, Needed: 0.12.0 <= x < 0.13
Make sure you install it with python3
