### ISSUE TITLE
Pyqt problem when opening preferences on m1 mac

### ISSUE THREAD

**Issue by puruoni** [qtumproject/qtum-electrum#120]
https://github.com/spesmilo/electrum/issues/7725

Same as this issue.

https://github.com/spesmilo/electrum/pull/7727
Looks like this code has already been added,
Is this enough to correct the problem?

**Comment by icodeface** [comment]
yeah, https://github.com/spesmilo/electrum/pull/7727 has already been added, seems not related. 
uut i don't have a M1 mac to test, could u get any error logs ?

**Comment by icodeface** [comment]
the `_find_system_cameras` issue should be fixed https://github.com/qtumproject/qtum-electrum/commit/c5ea132f5f583fa3ec2af706fe94bfada93df64d

**Comment by icodeface** [comment]
and maybe try 
```
mkdir ~/lib
ln -s $(brew --prefix zbar)/lib/libzbar.dylib ~/lib/libzbar.dylib
```
to fix the zbar issue on M1

**Comment by puruoni** [comment]
> and maybe try
mkdir ~/lib
ln -s $(brew --prefix zbar)/lib/libzbar.dylib ~/lib/libzbar.dylib
to fix the zbar issue on M1

This solved the problem.
```
brew install zbar
```

And, with the master, I was able to show preferences!!

<img width="821" alt="スクリーンショット 2022-12-05 18 40 02" src="https://user-images.githubusercontent.com/54670037/205604465-a67e0217-ba52-4a10-88a7-b36e7d492efc.png">
