### ISSUE TITLE
Unable to change staker with ledger

### ISSUE THREAD

**Issue by puruoni** [qtumproject/qtum-electrum#121]
I'm using Ledger to delegate with the following reference.
The Ledger app and Ledger Loader are up to date.
https://blog.qtum.org/qtum-ledger-loader-address-delegation-with-ledger-and-qrc20-tokens-with-ledger-7cd85083b2f4

When I try to change the Staker in the delegate tab, "Confirm Transaction on your Ledger device..." is displayed and Ledger does not respond.

No problems with normal transfers or starting a delegate with a different address.

Is this due to the number of split UTXOs that the address has already delegated, causing the Ledger to stop responding, or is it simply due to the slow response?
I have about 9000 UTXOs and have already received rewards with about 1600 transactions.

**Comment by icodeface** [comment]
sign delegate transaction could take more time, you can wait longer and see if it works

**Comment by puruoni** [comment]
Thanks for your reply.
OK, I waited an hour but I'll wait longer anyway...

**Comment by puruoni** [comment]
Tried twice and got this error both times. Cannot get a normal response due to an address with a large number of UTXOs?

![image](https://user-images.githubusercontent.com/54670037/205906002-acabad4a-61b3-48bf-93fc-1afd550f76ea.jpeg)

**Comment by icodeface** [comment]
and did your Ledger response normally after waiting a longer time ?

**Comment by puruoni** [comment]
Looking at the network dialog, it seems to be connecting to the node with no problem.
Anyway, Ledger is not responding.

The transaction size is 1552541bytes, so it might be a problem with the request size limit or something.

**Comment by icodeface** [comment]
> Looking at the network dialog, it seems to be connecting to the node with no problem. Anyway, Ledger is not responding.
> 
> The transaction size is 1552541bytes, so it might be a problem with the request size limit or something.

you can try broadcast the transaction manually in https://qtum.info/misc/toolbox/send-raw-tx, then we can see if it a network request issue.

**Comment by puruoni** [comment]
Yeah, I tried to export it and send it from qtum.info, but got "request entity too large"...

![qtum](https://user-images.githubusercontent.com/54670037/206082669-ee121133-a1de-44da-a48b-8d6f90eb2076.png)

**Comment by puruoni** [comment]
Maybe I need to include all the split UTXOs in the transaction, 
so I'll try to merge some UTXOs and reduce the transaction size.

**Comment by icodeface** [comment]
@puruoni   Let's try this:
1. View => Show Coins
2. select a small amount of UTXOs with the sum about 1 QTUM
3. change delegation staker with Ledger

**Comment by puruoni** [comment]
@icodeface 
I didn't know about this tab...
You saved my day... Thanks a million!!

**Comment by icodeface** [comment]
> @icodeface I didn't know about this tab... You saved my day... Thanks a million!!

glad to hear it works
