### ISSUE TITLE
None of this work.

### ISSUE THREAD

**Issue by mbalance** [qtumproject/qtum-electrum#40]
Tried both options from the instructions on my Ubuntu 16.04 LTS and none of them worked.

`./electrum
bash: ./electrum: Permission denied`

I also tried the dev version, I get so many pip errors it's simply stupid and after fixing one the next one comes up.

Fucking waste of time...

**Comment by mbalance** [comment]
Is this place dead?

`root@wallets-VirtualBox:/home/wallets/qtum-electrum-0.17.4.2# ./electrum
bash: ./electrum: Permission denied`

**Comment by icodeface** [comment]
README.md updated
