### ISSUE TITLE
Can't update from Standard wallet

### ISSUE THREAD

**Issue by sundevil1** [qtumproject/qtum-electrum#43]
I can't update my standard wallet. It only creates a new one with a different address. The standard one won't show my MED tokens that was sent 3 days ago. I have QTUM in my wallet.  Thanks

**Comment by icodeface** [comment]
qtum electrum doesn't support QRC20 tokens yet.
but don't worry, your tokens are not lost,,just not showed in your wallet.
you can wait for the new qtum electrum release.
another way is to export your private key and import to Qtum Core wallet.

**Comment by sundevil1** [comment]
Thank you for your fast response and I am glad they are not lost. How do I
export your private key and import them to Qtum core wallet?  Do you have a
video or instructions to walk me through it?

Thanks again, Ralph Montoya

**Comment by icodeface** [comment]
@sundevil1 
In qtum electrum you can go to Wallet > Private Keys > Export to export the private keys.
Import to qtum core wallet is the same as bitcoin, you can refer  to [https://bitcoin.stackexchange.com/questions/5941/how-do-i-import-a-private-key-into-bitcoin-qt](https://bitcoin.stackexchange.com/questions/5941/how-do-i-import-a-private-key-into-bitcoin-qt)

**Comment by sundevil1** [comment]
Hello, I still can not see my MED I sent to my Qtum electrum wallet. Do you
know when the release will be if it has not happened yet?  Thanks again

**Comment by icodeface** [comment]
you can refer to https://github.com/qtumproject/qtum-electrum/issues/45
after import the private to Qtum Core wallet, you should "Add Token" manually.

**Comment by icodeface** [comment]
you can also import your private key to [Qtum Web Wallet](https://qtumwallet.org/)

**Comment by icodeface** [comment]
@sundevil1 new release published, you can have a try. https://github.com/qtumproject/qtum-electrum/releases/tag/v0.18.0

**Comment by sundevil1** [comment]
I have started a new Qtum Core wallet. I have Qtum in it. I set up the MED
token in it. I tried to manually transfer my MED to the new wallet from my
Qtum Electrum wallet and it keeps saying my Private Key is wrong. I
followed your instructions on copying it and it still will not work.

Is there an easy way to just update the Qtum Electrum wallet to hold MED
tokens?

Thanks, Ralph

**Comment by icodeface** [comment]
Qtum Electrum supports erc20 tokens now, you can just send your MED to the qt wallet rather than dumping the private key. 
https://github.com/qtumproject/documents/blob/master/en/Qtum-Electrum-User-Guide.md#qrc20-token
