### ISSUE TITLE
Emergency: receiving token problem

### ISSUE THREAD

**Issue by KaizenPath** [qtumproject/qtum-electrum#45]
Hi, i am a qtum electrum wallet user, i made a withdrawal transfer from mi all coin account and this is the TXID: 6e76c1c7afaf18c774a6106cfc4d9006551cba65f285e1a847a7774119ea258a

I was ell done with all data correct to this account QYPA9pCj3mJXRqQ3sUaGCsx2EmvWidZehR
But the withdrawal never arrived to my qtum electrum wallet. Please which has been the problem? may we solve it? sxuppously qtum electrum wallet is a qtum wallet, what can we do?

![image 2018-02-16 20 12 15](https://user-images.githubusercontent.com/36548174/36324719-af5ee7ee-1355-11e8-9b5c-dae3c7a0c2d4.jpg)

**Comment by KaizenPath** [comment]
QYPA9pCj3mJXRqQ3sUaGCsx2EmvWidZehR this is my qtum electrum ardes

**Comment by icodeface** [comment]
Hi, qtum electrum doesn't support qrc20 tokens yet, but don't worry, your tokens will never be lost.
You can wait some time (may be a month) for the qtum electrum updates, we have a plan to support qrc20 tokens.
Another suggestion is  dumping your private key from qtum electrum, and import it to [Qtum Core Wallet](https://github.com/qtumproject/qtum/releases)

**Comment by KaizenPath** [comment]
Oh god! Thanks for the info and the good new!! :)

May you tell my how can i dump it into qtum core wallet please??

Enviado desde mi iPhone

El 17 feb 2018, a las 14:58, 代码脸 <notifications@github.com<mailto:notifications@github.com>> escribió:


Hi, qtum electrum doesn't support qrc20 tokens yet, but don't worry, your tokens will never be lost.
You can wait some time (may be a month) for the qtum electrum updates, we have a plan to support qrc20 tokens.
Another suggestion is dumping your private key from qtum electrum, and import it to Qtum Core Wallet<https://github.com/qtumproject/qtum/releases>

**Comment by icodeface** [comment]
@KaizenPath
For dumping private keys go to "Qtum Electrum" => "Wallet" => "Private keys" => "Export".
For importing private key go to "Qtum Core" => "Help" => "Debug window" => "Console" and type `importprivkey "your key"`
Once done, you can go to "QRC Tokens" => "Add Token" to add your SPC token and select the right address.

**Comment by KaizenPath** [comment]
I managed tonsolve the problem, i really apreciste your  help, speed and profesionallity. Thanks very much :)

Enviado desde mi iPhone

El 18 feb 2018, a las 18:00, 代码脸 <notifications@github.com<mailto:notifications@github.com>> escribió:


@KaizenPath<https://github.com/kaizenpath>
For dumping private keys go to "Qtum Electrum" => "Wallet" => "Private keys" => "Export".
For importing private key go to "Qtum Core" => "Help" => "Debug window" => "Console" and type importprivkey "your key"
Once done, you can go to "QRC Tokens" => "Add Token" to add your SPC token and select the right address.

**Comment by icodeface** [comment]
new release published, qrc20 token supported. https://github.com/qtumproject/qtum-electrum/releases/tag/v0.18.0
