### ISSUE TITLE
Failed to compile output issue

### ISSUE THREAD

**Issue by cupid-stunt** [qtumproject/qtum-electrum#46]
Got a major problem with the wallet. I installed the wallet using a Trezor on MACos and around Christmas time I uploaded some Qtum to the wallet. This week I am trying to move the Qtum to a Ledger nano. Everything seems fine until I try and send the transaction where I get a "failed to compile output" warning. I've scoured the net trying to find a solution but even though it is a known issue and attempts to solve it in my case fail. I have installed a new wallet in Windows and with the Trezor, I can see the coins but I still get the same warning. I suspect the Private keys held in the Trezor keeps the coins safe and if I can use another Trezor supported wallet then maybe i'm able to access them. Anyone know of another Trezor supported Qtum wallet?

**Comment by icodeface** [comment]
Hi, I don't know whether qtum electrum supports Trezor or not , because I have't got a Trezor to test.
But ledger should works fine. Can you post more info about the ledger issue

**Comment by icodeface** [comment]
Ordered a Trezor, will check later.

**Comment by cupid-stunt** [comment]
There's no issue with the Ledger. Its the Trezor/Qtum-Electrum wallet combination thats the problem. I'll post more details later when I have the time; including screen shots etc. Thanks for the reply!

**Comment by cupid-stunt** [comment]
So when I connect the Trezor, I get access to the coins but I also get this warning.

![q1](https://user-images.githubusercontent.com/17929084/37056195-b55fc0e4-2194-11e8-83e0-a91d0efa8f54.jpeg)

If I select "sign". My Trezor is accepted and the Trezor icon turns green.

![q4](https://user-images.githubusercontent.com/17929084/37056278-fb20dffa-2194-11e8-966d-731971e035f7.jpeg)

Trying to send the coins receives the error, "Failed to compile output".

![q9](https://user-images.githubusercontent.com/17929084/37056335-2cd0bc78-2195-11e8-9956-52d443cecc19.png)

Appreciate the help please! It's only a small amount ($50) but its still irritating.

**Comment by cupid-stunt** [comment]
@icodeface Thank you very much! please drop your BTC or QTUM etc. address and i'll buy you a coffee!

**Comment by icodeface** [comment]
@cupid-stunt You are welcome, QTrpgkRjmqbvrpFmJboPsBZtpQpwtRHfab.

**Comment by cupid-stunt** [comment]
How do I update the program in MACos?

**Comment by icodeface** [comment]
I will publish a release next week, then you can just download from https://github.com/qtumproject/qtum-electrum/releases and install it.

**Comment by icodeface** [comment]
@cupid-stunt new release published, you can have a try. https://github.com/qtumproject/qtum-electrum/releases/tag/v0.18.0

**Comment by cupid-stunt** [comment]
Ok, I cancelled the initial send as the address was different, but then I read your release info re the BTC address and checked with a small amount. All went through fine. Thanks for fixing it, I've sent you a small amount for your trouble.
