### ISSUE TITLE
Invalid Address Msg when adding contract address

### ISSUE THREAD

**Issue by R8Safee** [qtumproject/qtum-electrum#47]
QTUM Electrum Version 3.1.0
Standard wallet, non-segwit 
Installed on a Win 10 Professional 
Version	10.0.16299 Build 16299

Steps taken:
![capture](https://user-images.githubusercontent.com/37427760/37500588-b0a58b8e-28a0-11e8-9dd0-d2bbf7d4bb1c.PNG)
![capture1](https://user-images.githubusercontent.com/37427760/37500596-bb9f2ba8-28a0-11e8-8a47-24489577885e.PNG)
![capture2](https://user-images.githubusercontent.com/37427760/37500598-bfb2f7d8-28a0-11e8-91a3-52d5006c3b76.PNG)

The contract address and name is taken directly from https://explorer.qtum.org/token/4060e21ac01b5c5d2a3f01cecd7cbf820f50be95/read-smart-contract

**Comment by icodeface** [comment]
@R8Safee Hi, what you added is "Contact" not "Contract", and you used Electrum but not [Qtum Electrum](https://github.com/qtumproject/qtum-electrum/releases/tag/v0.18.0).
![image](https://user-images.githubusercontent.com/9477987/37507523-d8e3b7e0-2929-11e8-984f-e6d52fc9f928.png)
