### ISSUE TITLE
Lost Address

### ISSUE THREAD

**Issue by R8Safee** [qtumproject/qtum-electrum#48]
Created a new wallet and added a smart contact for PUT. 
Sent a small amount from another wallet and when I tried to use QTUM-Electrum to check it froze and crashed for unknown reason. Most likely it was due to pc and all of the apps I was running.
Restarted the app and the smart contact wallet address is missing.
Re-added the smart contact but now the wallet address is missing.
Restarted the app to make sure second wallet address does not disappear - it remained in app.

How do I retrieve the previous address and re-associate it to the app?

First address is QZrn7KmcDQQBZJwYFYPMG3B3sMhQGgbrDe
Second address is QW9ry2hsUtVEgXxaJMk3xTbRDtwmh65f1D

**Comment by icodeface** [comment]
<img width="521" alt="wx20180321-110854 2x" src="https://user-images.githubusercontent.com/9477987/37693101-742637b0-2cf8-11e8-8218-74f1ca8da603.png">
you can get all your addresses here
