### ISSUE TITLE
QTUM electrum wallet not connected

### ISSUE THREAD

**Issue by silversurfer777** [qtumproject/qtum-electrum#50]
I just created a QTUM Electrum wallet and its stating not connected, I did a internet search and it appears the Electrum wallet has been working on their severs since December. 
 Anyone able to connect to check their balance.

**Comment by icodeface** [comment]
Hi @silversurfer777 , do you use the latest qtum electrum version ? And can you send more info about your issue ?

**Comment by icodeface** [comment]
@silversurfer777 works fine on my side, which os do you use ? and if the OS is Linux or Mac, please try running Qtum Electrum from the terminal with the -v flag and paste logs. Otherwise, is there any chance you could try opening the wallet file on a Linux machine with -v

**Comment by Dominic2015** [comment]
Doesnt work
