### ISSUE TITLE
OSX version of Qtum Electrum 0.18.2 crashes

### ISSUE THREAD

**Issue by palobern** [qtumproject/qtum-electrum#51]
0.18.1 works well, but 0.18.2 crashes on my Sierra 10.12.6 during the first launch.

See attached crash log 
[electrum_crash.txt](https://github.com/qtumproject/qtum-electrum/files/1951396/electrum_crash.txt)

**Comment by icodeface** [comment]
@palobern Thanks for reporting, 0.18.2 can only run on OSX High Sierra. I will make a new release to fix this soon.
