### ISSUE TITLE
QTUM Addresses Beginning With "M"

### ISSUE THREAD

**Issue by JB395** [qtumproject/qtum-electrum#52]
A user reported a QTUM address beginning with an "M" created by the Electrum wallet, such as MEUpxFraYcLQMnXQxiwRhWx6NkNmvU8s6H

This address appears to be a valid address and work for transactions, but is disconcerting to the user.

Here is a screen shot from the user:

![electrum addresses 4-29-2018](https://user-images.githubusercontent.com/29760787/39406041-6daace1a-4b7e-11e8-88ee-b89a961874df.jpg)

**Comment by icodeface** [comment]
i think it is segwit addresses, where did you get the seed phrase ?
