### ISSUE TITLE
Electrum Qtum Wallet MED tokens issue

### ISSUE THREAD

**Issue by Jester78** [qtumproject/qtum-electrum#53]
Hi,

I have a problem sending MED tokens from my Electrum Qtum wallet to Gate.io. The error message is: 

choose_buckets - sender address has no u txo

Can anyone help, please?

Thanks
Jester78

**Comment by icodeface** [comment]
Hi @Jester78 , you need some qtum in your MED bind address to pay for the gas fee.

**Comment by Jester78** [comment]
Hi,
great thank you very much. Now it was ok. Have a nice day
