### ISSUE TITLE
Wrong address path for selected coin

### ISSUE THREAD

**Issue by EGOISTK21** [qtumproject/qtum-electrum#56]
device: trezor one
firmware: v1.6.1

qtum-electrum version 0.18.4
on Windows and macOS

When I click on the display address, the trzor screen shows the wrong address path for the selected coin.
When you click Continue, the address shown on the trevor screen (headed by m) is different from the actual address on the computer (headed by q).

![IMG_1413.jpg](https://i.loli.net/2018/06/26/5b31b48e02bce.jpg)
![IMG_9265.jpg](https://i.loli.net/2018/06/26/5b31b48e845e0.jpg)

**Comment by icodeface** [comment]
Hi @EGOISTK21 , check the issue again, the fact is that trezor doesn't support Qtum officially, Qtum Electrum uses bitcoin mode in trezor for now.

**Comment by phoniex1** [comment]
你好，我最近在学习量子链，但是发现trezor暂时不支持量子链。又搜到这个项目好像有Trezor支持的代码，想进一步跟你沟通一下，能方便留个联系方式吗？

**Comment by icodeface** [comment]
@phoniex1 aUBjb2RlZmFjZS5jbg==

**Comment by phoniex1** [comment]
Hello, @icodeface ，
Sorry to leave a message in Chinese.
I was learning quantum chain recently， but found that trezor does not support quantum chain currently. Again found this project seems to have Trezor support code of quantum, I want to communicate with you further, can easily leave a contact? 
Thank you!

**Comment by icodeface** [comment]
@phoniex1 base64 decode the previous message, you will get my email address.
