### ISSUE TITLE
ImportError no module named 'eth_abi' on Android device

### ISSUE THREAD

**Issue by xuzhitong** [qtumproject/qtum-electrum#59]
When I run contrib/make_apk to debug on android mobile,the app crashed.I checked the log and found some error as below:
07-12 14:55:22.247   754   754 I cnss-daemon: NDA_LLADDR received\r
'b'07-12 14:55:22.741 27620 27660 I python  : Traceback (most recent call last):
07-12 14:55:22.741 27620 27660 I python  :   File "main.py", line 75, in <module>\r
'b'07-12 14:55:22.742 27620 27660 I python  :     imp.load_module(\'qtum_electrum\', *imp.find_module(\'lib\'))
07-12 14:55:22.742 27620 27660 I python  :   File "/data/user/0/org.qtum.qelectrum/files/app/crystax_python/stdlib.zip/imp.py", line 244, in load_module
07-12 14:55:22.742 27620 27660 I python  :   File "/data/user/0/org.qtum.qelectrum/files/app/crystax_python/stdlib.zip/imp.py", line 216, in load_package
07-12 14:55:22.742 27620 27660 I python  :   File "<frozen importlib._bootstrap>", line 693, in _load
07-12 14:55:22.743 27620 27660 I python  :   File "<frozen importlib._bootstrap>", line 673, in _load_unlocked\r
'b'07-12 14:55:22.743 27620 27660 I python  :   File "<frozen importlib._bootstrap_external>", line 662, in exec_module
07-12 14:55:22.743 27620 27660 I python  :   File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
07-12 14:55:22.743 27620 27660 I python  :   File "./lib/__init__.py", line 3, in <module>\r
'b'07-12 14:55:22.744 27620 27660 I python  :     from .wallet import Synchronizer, Wallet
07-12 14:55:22.744 27620 27660 I python  :   File "./lib/wallet.py", line 44, in <module>
07-12 14:55:22.744 27620 27660 I python  :     from .qtum import *
07-12 14:55:22.744 27620 27660 I python  :   File "./lib/qtum.py", line 7, in <module>
07-12 14:55:22.744 27620 27660 I python  :     from eth_abi import encode_abi
### _**07-12 14:55:22.745 27620 27660 I python  : ImportError: No module named \'eth_abi\'\r**_
'b'07-12 14:55:22.801 27620 27660 I python  : Python for android ended.\rom .qtum import *
07-12 14:55:22.744 27620 27660 I python  :   File "./lib/qtum.py", line 7, in <module>
07-12 14:55:22.744 27620 27660 I python  :     from eth_abi import encode_abi
07-12 14:55:22.745 27620 27660 I python  : ImportError: No module named \'eth_abi\'\r
'b'07-12 14:55:22.801 27620 27660 I python  : Python for android ended.\r

I checked the requirements.txt,but there is no eth_api found.
What should I do to import 'eth-api'?

**Comment by icodeface** [comment]
you can refer to the windows build script [prepare-eth-abi.sh](https://github.com/qtumproject/qtum-electrum/blob/master/contrib/build-wine/prepare-eth-abi.sh).

but btw, qtum electrum doesn't have an android release yet, even if fix the eth_abi module issue, i think there should be many other issues.

**Comment by Edison4mobile** [comment]
I am still having same error.
