### ISSUE TITLE
can't send token

### ISSUE THREAD

**Issue by TuoUP** [qtumproject/qtum-electrum#60]
I got into trouble with send Token,i successfully installed the software on Ubuntu16.04,but when I send Token in test net , There appears a bug,the track back infomation like this:

Traceback (most recent call last):
  File "/home/tete/Desktop/newvenv/origin/qtum-electrum/qtum_electrum/gui/qt/main_window.py", line 3164, in _smart_contract_broadcast
    sender=sender)
  File "/home/tete/Desktop/newvenv/origin/qtum-electrum/qtum_electrum/wallet.py", line 1196, in make_unsigned_transaction
    fee_estimator, self.dust_threshold(), sender)
  File "/home/tete/Desktop/newvenv/origin/qtum-electrum/qtum_electrum/coinchooser.py", line 223, in make_tx
    self.penalty_func(tx), sender)
  File "/home/tete/Desktop/newvenv/origin/qtum-electrum/qtum_electrum/coinchooser.py", line 365, in choose_buckets
    return strip_unneeded(selected, sufficient_funds, sender)
  File "/home/tete/Desktop/newvenv/origin/qtum-electrum/qtum_electrum/coinchooser.py", line 83, in strip_unneeded
    if not sufficient_funds(bkts[i + 1:]):
  File "/home/tete/Desktop/newvenv/origin/qtum-electrum/qtum_electrum/coinchooser.py", line 216, in sufficient_funds
    total_input = sum(bucket.value for bucket in buckets)
  File "/home/tete/Desktop/newvenv/origin/qtum-electrum/qtum_electrum/coinchooser.py", line 216, in <genexpr>
    total_input = sum(bucket.value for bucket in buckets)
AttributeError: 'str' object has no attribute 'value'

AFTER this , i try to print the elements in Buckets,then I found the item at last is my address,

####buckets item #####
Bucket(desc='qdBDeM1aJgbTvLsgZbu6cnk5WCKqhTX8zy', size=148, value=741000, coins=[{'num_sig': 1, 'type': 'p2pkh', 'height': 178608, 'prevout_n': 1, 'x_pubkeys': ['ff043587cf035252541a80000000dfa62369aa98c14d99cdd059fa3ad2bf1661791b53e535bccbed4d95695e0c58024c9858692ab58356f63d05feb388094a13b5859f9e8314f751cd7648101540eb00001300'], 'value': 741000, 'prevout_hash': 'b66a9bd81de1676e1bad84229e9fc75bc27f03638b292ac70aed3ae3bc8c8bc2', 'coinbase': False, 'signatures': [None], 'address': 'qdBDeM1aJgbTvLsgZbu6cnk5WCKqhTX8zy'}])
####buckets item #####
Bucket(desc='qdBDeM1aJgbTvLsgZbu6cnk5WCKqhTX8zy', size=148, value=741000, coins=[{'num_sig': 1, 'type': 'p2pkh', 'height': 178608, 'prevout_n': 1, 'x_pubkeys': ['ff043587cf035252541a80000000dfa62369aa98c14d99cdd059fa3ad2bf1661791b53e535bccbed4d95695e0c58024c9858692ab58356f63d05feb388094a13b5859f9e8314f751cd7648101540eb00001300'], 'value': 741000, 'prevout_hash': 'b66a9bd81de1676e1bad84229e9fc75bc27f03638b292ac70aed3ae3bc8c8bc2', 'coinbase': False, 'signatures': [None], 'address': 'qdBDeM1aJgbTvLsgZbu6cnk5WCKqhTX8zy'}])
####buckets item #####
Bucket(desc='qT1c7kbJ5o19XgfqYB3KsXGuqTHs9LQLKD', size=148, value=1848076100, coins=[{'num_sig': 1, 'type': 'p2pkh', 'height': 178576, 'prevout_n': 1, 'x_pubkeys': ['ff043587cf035252541a80000000dfa62369aa98c14d99cdd059fa3ad2bf1661791b53e535bccbed4d95695e0c58024c9858692ab58356f63d05feb388094a13b5859f9e8314f751cd7648101540eb01000200'], 'value': 1848076100, 'prevout_hash': '98de1dea4c99f8d1ce5f76c6a86bc8a4bdac05df4647a4c9926dcc657c99dc59', 'coinbase': False, 'signatures': [None], 'address': 'qT1c7kbJ5o19XgfqYB3KsXGuqTHs9LQLKD'}])
####buckets item #####
qdBDeM1aJgbTvLsgZbu6cnk5WCKqhTX8zy

IN ADDTION,i try to send Qtum to others ,everything works well!!!

**Comment by icodeface** [comment]
checking

**Comment by icodeface** [comment]
cannot reproduce on my side, did you use the latest code of the master branch ?

**Comment by icodeface** [comment]
thanks for reporting, fixed
