### ISSUE TITLE
Does not send MED tokens

### ISSUE THREAD

**Issue by GeminiRos** [qtumproject/qtum-electrum#61]
When sending, I get this information - "str' object has no attribute 'value'

Video in zip file
[MED_Token_Send.zip](https://github.com/qtumproject/qtum-electrum/files/2217923/MED_Token_Send.zip)

**Comment by icodeface** [comment]
duplicated with #60

**Comment by GeminiRos** [comment]
On MacOS, the problem still exists in Beta 0.18.5

**Comment by icodeface** [comment]
if you are urgent, send some qtum(>0.11) to your MED bind address can fix it.
