### ISSUE TITLE
Electrum bitcoin wallet phishing attack

### ISSUE THREAD

**Issue by JB395** [qtumproject/qtum-electrum#86]
The Electrum bitcoin wallet had a phishing attack and mitigations described below. Should these mitigations be updated for Qtum Electrum?

https://github.com/spesmilo/electrum/issues/4968

https://github.com/spesmilo/electrum/issues/4953

qt: show_message and friends display plaintext by default
https://github.com/spesmilo/electrum/commit/5dc240d4ed39796bec72ac115d920160865b3ec5
SomberNight committed 13 days ago
  
gui: prepend broadcast_transaction errors with explanatory message
https://github.com/spesmilo/electrum/commit/5248613e9d7b8b8ec85a1cee897d1901d747f5b4
SomberNight committed 13 days ago
  
kivy network dialog: update server and proxy properly  …
https://github.com/spesmilo/electrum/commit/b491a30dd9f550ab2f335ae88889c910125d4559
SomberNight committed 13 days ago

**Comment by icodeface** [comment]
@JB395 thanks for reporting, it's already fixed by https://github.com/qtumproject/qtum-electrum/commit/fef577cd0820eb6344483c596127c16855278ea4 , new release is coming soon.
