### ISSUE TITLE
Qtum electrum wallet

### ISSUE THREAD

**Issue by patrick2904** [qtumproject/qtum-electrum#92]
trying to reclaim my wallet ( desktop) after computer crash. Downloaded the wallet and got an icon on the desktop but it won't open. I've got all the password and passphrases

**Comment by icodeface** [comment]
Hi @patrick2904 , which OS are you using ? and can you try run qtum-electrum using command line and post the outputs ?

**Comment by patrick2904** [comment]
I am trying to get this on my desktop computer. I use google chrome for the
browser.It is windows 10 OS.
I have tried to restore wallet. but can't seem to get the wallet on desktop
to open.

Patrick

**Comment by patrick2904** [comment]
I have also downloaded a core wallet. Is it possible to get the qtum tokens
to move to that wallet?
I can open the core and it's attached to the taskbar. I can NOT open the
electrum wallet

Patrick

**Comment by icodeface** [comment]
@patrick2904 did you try the old version qtum electrum ? [v0.18.11](https://github.com/qtumproject/qtum-electrum/releases/tag/v0.18.11) and [v0.18.10](https://github.com/qtumproject/qtum-electrum/releases/tag/v0.18.10)

**Comment by patrick2904** [comment]
Tried v0.18.12. Doesn't open on desktop
Patrick

**Comment by patrick2904** [comment]
That seemed to work,
Thank you

Patrick
